### ISSUE TITLE
Signal callback parameter support

### ISSUE THREAD

**Issue by Place1** [Place1/node-gir#1]
Currently you can connect signals using `instance.connect('signal-name', () => console.log('some callback'))` but there is no support for converting the original native signal parameters to JS values.

An example test case has been written to outline this: https://github.com/Place1/node-gir/blob/6078d32bf1f91498a6e8f24d8288fbf4e2a880a7/__tests__/signals.test.js#L19

In [types/object.cc](https://github.com/Place1/node-gir/blob/6078d32bf1f91498a6e8f24d8288fbf4e2a880a7/src/types/object.cc#L485) there's a `Connect` method that will be added to the object's prototype (so that JS can call `instance.connect()`), This function will create a `GIRSignalClosure` and then connect it to the signal. The signal closure's job is to marshal the native signal callback into the JS callback it wraps. The [signal_closure.cpp](https://github.com/Place1/node-gir/blob/6078d32bf1f91498a6e8f24d8288fbf4e2a880a7/src/signal_closure.cc#L32) file outlines this marshalling.

Currently i'm using the GI information about the signal to loop over the expected native parameters to create a list of Local<Value> objects (JS values) that will then be passed to the JS callback when it gets invoked.

I'm converting the native values to JS values using [GIRValue::FromGValue()](https://github.com/Place1/node-gir/blob/6078d32bf1f91498a6e8f24d8288fbf4e2a880a7/src/signal_closure.cc#L32) but its implementation has a few issues

I could use some help on this issue :D

**Comment by Place1** [comment]
@jamrizzi this issue is important, if we can get signals working then `react-native-gtk` can start using my `node-gir` fork :D

**Comment by Place1** [comment]
So i've made a bunch of progress on this, most (maybe all) fundamental types (number, string, boolean etc) are working. GObject's also work as parameters. GStruct's currently do not! GIRStruct needs a big refactor. It is very similar to GIRObject so I really want to find a way that they can share the general structure/implementation design, but it's not as straightforward as using inheritance because the underlying APIs aren't polymorphic! Once i come up with a good idea for the architecture behind GIRStruct/GIRObject then i'll do the refactor and this feature will be working!

@jamrizzi if you want to look into how i've changed GIRObject you might get a better idea of how GIRStruct would be refactored. The thing i'm trying to avoid is just copy-pasting the changes from GIRObject into GIRStruct as that will be a maintenance painpoint. Ideally they should share a bunch of code (good code design and reuse), so if you have some thoughts on how to achieve this that'd be amazing!

**Comment by jamrizzi** [comment]
Yes, I'll be looking into it this week.
