### ISSUE TITLE
memory safety and failure handling

### ISSUE THREAD

**Issue by Place1** [Place1/node-gir#10]
The codebase currently does an extremely poor job in terms of memory safety and handling failure conditions. Given i'm not a great c++ developer i've been researching some best practices and approaches. Here's what i'm thinking of introducing to help move the codebase towards a better state in this regard.

[cpp core guidelines](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#i10-use-exceptions-to-signal-a-failure-to-perform-a-required-task) suggests to use exceptions to signal a failure to perform a required task (i.e. function needs to exit exit early and signal a failure). So we want to use c++ exceptions.

[How to: Design for Exception Safety](https://msdn.microsoft.com/en-us/library/hh279653.aspx) also outlines some clear guidelines on how to write code that will be safe when using c++ exceptions.

A key change that will need to be introduced into the codebase (likely over time) will be how glib memory is managed.

example:
```c++
GIFunctionInfo *info = g_object_info_get_method(object_info, i);
do_something(info);
g_base_info_unref(info);
```

In this example `do_something(info)` might fail and we will leak memory because we never `g_base_info_unref(info);`. Following the microsoft guidelines linked above we should make use of RAII principles.

```c++
auto info = std::unique_ptr<GIFunctionInfo, void(*)(GIBaseInfo*)>(g_object_info_get_method(object_info, i), g_base_info_unref);
do_something(info.get());
```

The above uses `std::unique_ptr` to handle cleaning up of the glib memory using a custom deleter function (`g_base_info_unref`) when the pointer is deallocated. In the case of an exception the stack will unwind and the pointer will be destroyed, cleaning up the glib memory (yay no leaks).

I find the above a bit ugly and hard to read, despite being the best practice (presumably, i'm a newb). It does make a lot of sense though!

We could easily implement a few utilities such as `g_base_info_unique_ptr()` to hide some of the custom deleter boilerplate which could help readability.

I'd love to hear some alternative thoughts to this though. For reference [gjs](https://github.com/GNOME/gjs) (also written in c++) uses a mix of error code values (retuning ints), enum return values (returning well known values), boolean return values, out argument values like `void do_something(int *error_code);` and generally all use `goto` within the function to handle resource cleanup if a failure flag has been set somewhere.

**Comment by jamrizzi** [comment]
There's an updated version of how to design for exception safety at https://docs.microsoft.com/en-us/cpp/cpp/how-to-design-for-exception-safety
