### ISSUE TITLE
Support callback arguments in bindings 

### ISSUE THREAD

**Issue by ewnd9** [Place1/node-gir#13]
Hi, trying to use `keybinder`

```js
'use strict';

const { load } = require('node-gir');
const gtk = load('Gtk', '3.0');
const keybinder = load('Keybinder', '3.0');

gtk.init(0);
keybinder.init(0);

const res = keybinder.bind('<Super>A', function() {
  console.log('hello');
}, null);
console.log(res);

gtk.main();
```

throws `Error: Unsupported GI Type: argument type "interface" is unsupported.`

Corresponding `gjs` script which works

```js
const Gtk = imports.gi.Gtk;
const Lang = imports.lang;
const Keybinder = imports.gi.Keybinder;

// https://github.com/rockon999/emoji-keyboard-gjs/blob/master/src/main.js
const Keyboard = new Lang.Class({
  Name: 'ek_EmojiKeyboard',
  Extends: Gtk.ApplicationWindow,
  _init: function (params) {
    this.parent(params);
    Keybinder.init();
    Keybinder.bind('<Super>A', Lang.bind(this, this._keybinding), null);
  },
  _keybinding: function () {
    print('<Super>A click');
  },
});

const Application = new Lang.Class({
  Name: 'EmojiKeyboard',
  Extends: Gtk.Application,
  vfunc_activate: function () {
    this.keyboard = new Keyboard({ application: this });
  }
});

new Application().run(ARGV);
```

I'm on Ubuntu 16.04 / node@8. Let me know if I missed something that could help.

**Comment by ewnd9** [comment]
Probably related to signals support? https://github.com/Place1/node-gir/issues/1

**Comment by Place1** [comment]
Yep that's it. I'll see if I can add support for it. In the mean time i've at least made the error message more descriptive :P

**Comment by Place1** [comment]
@ewnd9 i've added support for callbacks in this commit https://github.com/Place1/node-gir/commit/cb274c940382f6dc1a38797ed06a8ae2e8c6b373 but I haven't added support for argument/return value marshalling. So the bindings will call your callback function but they won't pass it any arguments or handle anything the JS function returns. I'm still figuring out the best way to implement the latter. I'm considering an FFI to GValue marshaller so I can reuse the existing code around closures that signals currently use.

**Comment by ewnd9** [comment]
Thanks, my example now works :tada:

**Comment by Place1** [comment]
That’s good to hear. Would you be interested at contributing to this
project?

**Comment by ewnd9** [comment]
Yep, I'm interested. There is little I can do with native/gtk but would love to help with js part.

**Comment by Place1** [comment]
It'd be good to find an example from GTK to make a testcase for callback arguments. We probably need the following tests to start with:
1. test('callbacks are called')
2. test('callbacks are passed arguments')
3. test('callback's return value is passed to native code')
    * this would require finding an example from GTK where the callback's return value is used in some way that we can assert about. Might be a hard one to test.

Hopefully 1. is passing, 2. and 3. should be failing currently until I get some time to implement them in the bindings :)

**Comment by Place1** [comment]
Callback arguments are now passed in by the bindings (c1370b34cc80b29c0083a18977b97e5038339356) @ewnd9 

I'd love to get some tests in the project for all of this but i'm not familiar enough with GTK or glib to know any examples.

**Comment by Place1** [comment]
@ewnd9 i've also pushed v0.1.5 to NPM so you can just npm install the package and you'll get these changes :)
