### ISSUE TITLE
Does this really work on all versions of node?

### ISSUE THREAD

**Issue by jamrizzi** [Place1/node-gir#20]
The package.json file says that all versions of node are supported.

```json
. . .
  "engines": {
    "node": "*"
  },
. . .
```

I don't know if that is a good idea because any version before node 4 is considered unstable, and node 4 is no longer active.

https://github.com/nodejs/Release

**Comment by jamrizzi** [comment]
NAN doesn't even support the first version of node. The earliest version it supports is `0.8`.

**Comment by Place1** [comment]
no it doesn't. I'm not officially planning to support a specific list of versions until the project is in a state that is usable. It's currently littered with memory leaks for example.

The CI runs against 6,8,9 currently.

**Comment by jamrizzi** [comment]
I suggest we support 6 and above

**Comment by Place1** [comment]
sure, update the engines in package.json but i'm not locking us into
supporting specific versions until the lib is stable.

**Comment by jamrizzi** [comment]
Yeah, I agree

**Comment by Place1** [comment]
idk if you want to open a PR for that but i'll close this issue :)
