### ISSUE TITLE
Eslint

### ISSUE THREAD

**Issue by jamrizzi** [Place1/node-gir#23]
As stated in issue #17, eslint should be added. I nominate using the Airbnb style guide. The code already seems to follow it closely. Any thoughts?

**Comment by Place1** [comment]
yeah that's fine with me

**Comment by jamrizzi** [comment]
I disabled the following airbnb rules.

[no-plusplus](https://eslint.org/docs/rules/no-plusplus)
[new-cap](https://eslint.org/docs/rules/new-cap)
[global-require](https://eslint.org/docs/rules/global-require)

**Comment by Place1** [comment]
Any reason to disable no-cap? Thats a pretty standard rule.

**Comment by jamrizzi** [comment]
Yes, there are classes coming from gobject that are not lowercase. I'm not exactly sure why. I can look into it further, but for now, the best temporary solution is to disable new-cap.

I could disable it with a comment if you want?

**Comment by Place1** [comment]
Nah that’s fine. We can always tighten it up later.
