### ISSUE TITLE
Plans for custom npm module?

### ISSUE THREAD

**Issue by jamrizzi** [Place1/node-gir#25]
I’m wondering, with the major changes and improvements being made, should we publish this as a separate npm module. It seems to me it might be cumbersome waiting for node-gir to accept the changes.

**Comment by Place1** [comment]
the `node-gir` name was already available on npm, the original author took `gir` so I figured i'd just publish to that: https://www.npmjs.com/package/node-gir

You can see that the `node-gir` package is from this repository :D

With that said, I haven't actually spoken with the original author about my fork but I'd be very happy to see what we can do together if he is keen. When I made the fork, the code didn't even compile so I didn't want to bother him with a million issues/pull requests given it hadn't been active for years; so i decided to just make it a hard fork.

**Comment by jamrizzi** [comment]
Ok, nice
