### ISSUE TITLE
Segmentation fault when tried to load Gio lib

### ISSUE THREAD

**Issue by cedlemo** [Place1/node-gir#35]
Here is the code that crash: 

```javascript
const { load, Gtk } = require('../');
const Gio = load('Gio');
```

I have the following error:

```
3500 segmentation fault (core dumped)  node hello_world.js
```

**Comment by cedlemo** [comment]
After some ugly printf debugging, it appears that the segmentation fault occurs when the GIFunction_info is loaded in `GIRFunction::prepare` and especialy when the `Nan` value name is set. Here is my disgusting printf instructions 

```c++
    printf("Set function name\n");
    const char *native_name = g_base_info_get_name(function_info);
    printf("-get_name\n");
    string js_name = Util::to_camel_case(string(native_name));
    printf("to_camel name %s \n", js_name.c_str());
    js_function->SetName(Nan::New(js_name.c_str()).ToLocalChecked());
    printf("set_name\n");
```

And the last output when it crashes:

```
Create function
Set function name
-get_name
to_camel name unixMountsChangedSince
set_name
function
Create function
Set function name
-get_name
to_camel name unixMountsGet
set_name
[1]    7435 segmentation fault (core dumped)  node hello_world.js
```

It would be great if you can give me the workflow you use in order to debug. Maybe I could be helpful (at least I am willing to try).

**Comment by Place1** [comment]
awesome. you can use the `backtrace` command inside gdb to get a more detailed stack trace. remember to build `node-gir` with `npm run build:debug`.

**Comment by Place1** [comment]
it seems that this is the problematic line:
https://github.com/Place1/node-gir/blob/master/src/types/struct.cpp#L73-L74

**Comment by cedlemo** [comment]
@Place1 ,

like in the issue #15, if I add the following instruction : `Gtk.main();` it does not crash ... heu ... which in fact make senses since `v8::internal::GlobalHandles::Destroy(v8::internal::Object**` is used when the nodejs VM clean it is environment, nonetheless this issue is the same than the issue #15.

**Comment by Place1** [comment]
ok, closing in favour of #15
