### ISSUE TITLE
Why is cmake-js a dev dependency?

### ISSUE THREAD

**Issue by cookiengineer** [Place1/node-gir#47]
In the package.json file `cmake-js` is a dependency, but grepping the codebase reveals that `cmake` is not used anywhere and all build related commands use `node-gyp`.

Why is cmake.js a dependency? Couldn't it be removed?

**Comment by Place1** [comment]
probably accidentally added it while experimenting with build systems early in this libs developments. it can be removed.

see the readme though, i dont really have the focus to work on this lib anymore :(
