### ISSUE TITLE
update README.md

### ISSUE THREAD

**Issue by Place1** [Place1/node-gir#7]
We should probably do a big update on the README.md as much of it is not correct anymore.

- [x] we should also add the circleci build status: `[![CircleCI](https://circleci.com/gh/Place1/node-gir/tree/master.svg?style=svg)](https://circleci.com/gh/Place1/node-gir/tree/master)`

- [x] add a contributing and roadmap section

- [x] setup guide for local developers

- [x] how to run tests

**Comment by jamrizzi** [comment]
I just added contributing guidelines #36

**Comment by Place1** [comment]
all done then
